
const data = [
    {
        "id": 1,
        "postpage" : "first",
        "thumbnailImg": "./images/post-img6.jpg",
        "category1": "Life",
        "categlry2": "Style",
        "cardtitle" : "첫번째 포스트입니다.",
        "authorImg" : "../../assets/profile.jpg",
        "authordd" : "Chilli",
        "authordt" : "Created",
        "authorDate" : "2022.05.25",
        "postDescription" : "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore illum nostrum perferendis voluptas, voluptate soluta corrupti dolore quidem. Placeat, eaque! Exercitationem estfacilis dolor quas odio cum incidunt repudiandae vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore illum nostrum perferendis voluptas, voluptate solutacorrupti dolore quidem. Placeat, eaque! Exercitationem est facilis dolor quas odio cum incidunt repudiandae vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventoreillum nostrum perferendis voluptas, voluptate soluta corrupti dolore quidem. Placeat, eaque! Exercitationem est facilis dolor quas odio cum incidunt repudiandae vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore illum nostrum perferendis voluptas, voluptate soluta corrupti dolore quidem. Placeat, eaque! Exercitationem est facilis dolor quas odio cum incidunt repudiandae vel.",
    },
    {
        "id": 2,
        "thumbnailImg": "./images/post-img5.jpg",
        "postpage" : "second",
        "category1": "Life",
        "categlry2": "Style",
        "cardtitle" : "두번째 포스트 입니다.",
        "authorImg" : "../../assets/profile.jpg",
        "authordd" : "Chilli",
        "authordt" : "Created",
        "authorDate" : "2022.05.28",
        "postDescription" : "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore illum nostrum perferendis voluptas, voluptate soluta corrupti dolore quidem. Placeat, eaque! Exercitationem estfacilis dolor quas odio cum incidunt repudiandae vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore illum nostrum perferendis voluptas, voluptate solutacorrupti dolore quidem. Placeat, eaque! Exercitationem est facilis dolor quas odio cum incidunt repudiandae vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventoreillum nostrum perferendis voluptas, voluptate soluta corrupti dolore quidem. Placeat, eaque! Exercitationem est facilis dolor quas odio cum incidunt repudiandae vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore illum nostrum perferendis voluptas, voluptate soluta corrupti dolore quidem. Placeat, eaque! Exercitationem est facilis dolor quas odio cum incidunt repudiandae vel.",
    },
    {
        "id": 3,
        "postpage" : "third",
        "thumbnailImg": "./images/post-img4.jpg",
        "category1": "Study",
        "categlry2": "Action",
        "cardtitle" : "세번째 포스트 입니다.",
        "authorImg" : "../../assets/profile.jpg",
        "authordd" : "Chilli",
        "authordt" : "Created",
        "authorDate" : "2022.06.04",
        "postDescription" : "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore illum nostrum perferendis voluptas, voluptate soluta corrupti dolore quidem. Placeat, eaque! Exercitationem estfacilis dolor quas odio cum incidunt repudiandae vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore illum nostrum perferendis voluptas, voluptate solutacorrupti dolore quidem. Placeat, eaque! Exercitationem est facilis dolor quas odio cum incidunt repudiandae vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventoreillum nostrum perferendis voluptas, voluptate soluta corrupti dolore quidem. Placeat, eaque! Exercitationem est facilis dolor quas odio cum incidunt repudiandae vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore illum nostrum perferendis voluptas, voluptate soluta corrupti dolore quidem. Placeat, eaque! Exercitationem est facilis dolor quas odio cum incidunt repudiandae vel.",
    },
    {
        "id": 4,
        "postpage" : "four",
        "thumbnailImg": "./images/post-img3.jpg",
        "category1": "Love",
        "categlry2": "Activity",
        "cardtitle" : "네번째 포스트 입니다.",
        "authorImg" : "../../assets/profile.jpg",
        "authordd" : "Chilli",
        "authordt" : "Created",
        "authorDate" : "2022.06.12",
        "postDescription" : "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore illum nostrum perferendis voluptas, voluptate soluta corrupti dolore quidem. Placeat, eaque! Exercitationem estfacilis dolor quas odio cum incidunt repudiandae vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore illum nostrum perferendis voluptas, voluptate solutacorrupti dolore quidem. Placeat, eaque! Exercitationem est facilis dolor quas odio cum incidunt repudiandae vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventoreillum nostrum perferendis voluptas, voluptate soluta corrupti dolore quidem. Placeat, eaque! Exercitationem est facilis dolor quas odio cum incidunt repudiandae vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore illum nostrum perferendis voluptas, voluptate soluta corrupti dolore quidem. Placeat, eaque! Exercitationem est facilis dolor quas odio cum incidunt repudiandae vel.",
    },
    {
        "id": 5,
        "postpage" : "five",
        "thumbnailImg": "./images/post-img2.jpg",
        "category1": "Social",
        "categlry2": "Style",
        "cardtitle" : "다섯번째 포스트 입니다.",
        "authorImg" : "../../assets/profile.jpg",
        "authordd" : "Chilli",
        "authordt" : "Created",
        "authorDate" : "2022.06.22",
        "postDescription" : "did ithdfkql fkdfkfcx,cv dfjd ockv df kqdkfkc.,!! perfct game diablo lol is hell github is so diffcultdipisicing elit. Inventore illum nostrum perferendis voluptas, voluptate soluta corrupti dolore quidem. Placeat, eaque! Exercitationem estfacilis dolor quas odio cum incidunt repudiandae vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore illum nostrum perferendis voluptas, voluptate solutacorrupti dolore quidem. Placeat, eaque! Exercitationem est facilis dolor quas odio cum incidunt repudiandae vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventoreillum nostrum perferendis voluptas, voluptate soluta corrupti dolore quidem. Placeat, eaque! Exercitationem est facilis dolor quas odio cum incidunt repudiandae vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore illum nostrum perferendis voluptas, voluptate soluta corrupti dolore quidem. Placeat, eaque! Exercitationem est facilis dolor quas odio cum incidunt repudiandae vel.",
    },
    {
        "id": 6,
        "postpage" : "six",
        "thumbnailImg": "./images/post-img1.jpg",
        "category1": "Life",
        "categlry2": "Style",
        "cardtitle" : "여섯째 포스트 입니다.",
        "authorImg" : "../../assets/profile.jpg",
        "authordd" : "Chilli",
        "authordt" : "Created",
        "authorDate" : "2022.07.01",
        "postDescription" : "동해물과백두산이 마르고 닳도록 하느님이 보우하사 우리나라 만세 무궁화 삼천리 화려강산 대한사랑 대한으로 길이 보전하세.",
    },
]

export default data